#!/bin/bash
export ANSIBLE_HOST_KEY_CHECKING=False

if [[ -z $NAME ]]; then
echo "You must set NAME to the agent subdomain. e.g. <NAME>.example.org"
exit 1
fi

if [[ -z $SECRET ]]; then
echo "You must set SECRET for api authentication"
exit 1
fi

if [[ ! -z $ANSIBLE_PRIVATE_KEY_FILE ]]; then
  echo "chmod 400 $ANSIBLE_PRIVATE_KEY_FILE"
  chmod 400 $ANSIBLE_PRIVATE_KEY_FILE
fi

if [[ ! -d tmp ]]; then
  mkdir tmp
fi

cat <<EOF > tmp/agents
[$HOST_GROUP]
$IP name=$NAME secret=$SECRET
EOF
ansible-playbook -i tmp/agents $PLAYBOOK_FILE $@
