#!/bin/bash
export ANSIBLE_HOST_KEY_CHECKING=False

function execute_playbook() {
  $PLAYBOOK/set_dns.sh
  ansible-playbook -i $PLAYBOOK/hosts.cfg $PLAYBOOK/site.yml $@
}


case `uname` in
  Linux)
    PLAYBOOK=$(dirname $(readlink -f $0))
    execute_playbook $@
    ;;
  Darwin)
    # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
    TARGET_FILE=$0

    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`

    # Iterate down a (possible) chain of symlinks
    while [ -L "$TARGET_FILE" ]
    do
      TARGET_FILE=`readlink $TARGET_FILE`
      cd `dirname $TARGET_FILE`
      TARGET_FILE=`basename $TARGET_FILE`
    done

    # Compute the canonicalized name by finding the physical path 
    # for the directory we're in and appending the target file.
    PHYS_DIR=`pwd -P`
    RESULT=$PHYS_DIR/$TARGET_FILE
    PLAYBOOK=$(dirname $RESULT)
    execute_playbook $@
    ;;
esac
