---
- hosts: agents
  user: root
  vars_files: [vars/all.yml, vars/agents.yml]
  roles: [common, docker, agent]

- hosts: databases
  user: root
  vars_files: [vars/all.yml, vars/databases.yml]
  roles: [common, mongodb]

- hosts: workers
  user: root
  vars_files: [vars/all.yml, vars/workers.yml]
  roles: [common, dns, worker]

- hosts: webservers
  user: root
  vars_files: [vars/all.yml, vars/webservers.yml]
  roles: [common, web]
