---
- hosts: agents
  user: root
  vars_files:
    - vars/app.yml
  vars: 
    github_repo: keyvanfatehi/saasbox-agent.git
    deploy_to: /opt/saasbox/agent
    verifies:
      - url: "https://{{ name }}.{{fqdn}}/api/v1/version"
        status: 200
    exposed_ports:
      - 22
      - 80
      - 443
  roles:
    - common
    - docker
    - haproxy
    - agent

- hosts: databases
  user: root
  vars_files:
    - vars/app.yml
  vars:
    exposed_ports:
      - 22
      - 27017
  roles:
    - common
    - mongodb

- hosts: workers
  user: root
  vars_files:
    - vars/app.yml
  vars: 
    github_repo: keyvanfatehi/saasbox-app.git
    deploy_to: /opt/saasbox/app
  roles:
    - common
    - worker

- hosts: webservers
  user: root
  vars_files:
    - vars/app.yml
  vars: 
    github_repo: keyvanfatehi/saasbox-app.git
    deploy_to: /opt/saasbox/app
    verifies:
      - url: "https://{{ name }}.{{ fqdn }}"
        status: 200
      - url: "https://{{ fqdn }}"
        status: 200
    exposed_ports:
      - 22
      - 80
      - 443
  roles:
    - common
    - web
