---
- hosts: agents
  user: root
  vars_files:
    - vars/app.yml
  vars: 
    project_name: saasbox-agent
    github_repo: keyvanfatehi/{{ project_name }}.git
    deploy_to: /opt/saasbox/agent
    verifies:
      - url: "https://{{ name }}.{{fqdn}}/api/v1/version"
        status: 200
  roles:
    - common
    - docker
    - haproxy
    - agent

- hosts: databases
  user: root
  vars_files:
    - vars/app.yml
  roles:
    - mongodb

- hosts: workers
  user: root
  vars_files:
    - vars/app.yml
  vars: 
    project_name: saasbox-app
    github_repo: keyvanfatehi/{{ project_name }}.git
    deploy_to: /opt/saasbox/app
  roles:
    - common
    - worker

- hosts: webservers
  user: root
  vars_files:
    - vars/app.yml
  vars: 
    project_name: saasbox-app
    github_repo: keyvanfatehi/{{ project_name }}.git
    deploy_to: /opt/saasbox/app
    verifies:
      - url: "https://{{ name }}.{{ fqdn }}"
        status: 200
      - url: "https://{{ fqdn }}"
        status: 200
  roles:
    - common
    - haproxy
    - web
