#!/usr/bin/env node
var repl = require('repl')
  , config = require('./etc/config')
  , mongoose = require('mongoose')
  , models = require('./src/server/models')

mongoose.connect(config.mongodb);
mongoose.connection.on('error', function(err) { throw err })

var r = repl.start({ prompt: "saasbox-"+process.env.NODE_ENV+" > " });

r.context.config    = config;
r.context.models    = models;
r.context.io        = require('./src/server/socketio');
r.context.dns       = require('./src/server/dns');
r.context.redis     = require('./src/redis');
r.context.products  = require('./products');
r.context.ejs       = require('ejs');
r.context.fs        = require('fs');
r.context.__        = require('lodash');
