#!/usr/bin/env node
var repl = require('repl')
  , config = require('./etc/config')
  , mongoose = require('mongoose')

mongoose.connect(config.mongodb);
mongoose.connection.on('error', function(err) { throw err })

var r = repl.start({ prompt: "saasbox-"+process.env.NODE_ENV+" > " });

r.context.app = require('./')
