#!/usr/bin/env node
var repl = require('repl')
  , config = require('./etc/config')
  , mongoose = require('mongoose')
  , models = require('./src/server/models')

mongoose.connect(config.mongodb);
mongoose.connection.on('error', function(err) { throw err })

var r = repl.start({ prompt: "saasbox-"+process.env.NODE_ENV+" > " });

r.context.config    = config;
r.context.io        = require('./src/server/socketio');
r.context.Instance  = models.Instance;
r.context.Account   = models.Account;
r.context.dns       = require('./src/server/dns');
r.context.redis     = require('./src/redis');
