---
- name: Restart SSH
  service: enabled=yes name=ssh state=restarted sleep=1

- name: Install node modules
  shell: "npm set registry {{ npm_registry }} && npm install"
  args:
    chdir: "{{ deploy_to }}"
  when: deploy_to is defined

- name: Restart supervisor
  service: enabled=yes name=supervisor state=restarted sleep=1
  tags: [restart]

- name: Pause
  pause: seconds=15
  when: verifies is defined

- name: Verify reachable
  shell: test $(curl -skL -w "%{http_code}" "{{ item.url }}" -o /dev/null) = "{{ item.status }}"
  with_items: verifies
  when: verifies is defined
