---
- name: Restart SSH
  service: enabled=yes name=ssh state=restarted sleep=1

- name: Install npm modules
  npm: >
    path="{{ deploy_to }}"
    production=yes
    registry="http://box.upstreamapp.com:4873/"
  when: deploy_to is defined

- name: Restart supervisor
  service: enabled=yes name=supervisor state=restarted sleep=1
  tags: [restart]

- name: Pause
  pause: seconds=15
  when: verifies is defined

- name: Verify reachable
  shell: test $(curl -skL -w "%{http_code}" "{{ item.url }}" -o /dev/null) = "{{ item.status }}"
  with_items: verifies
  when: verifies is defined
