---
- name: Install Ansible
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - ansible
    - python-pip

- name: Install httplib2 for Ansible
  pip: name=httplib2

- name: Copy supervisor config file
  template: src=supervisor/worker.conf
        dest=/etc/supervisor/conf.d/worker.conf
        owner=root group=root mode=0644
  notify: Restart supervisor
