---
zone: test.deadsimplecloud.com
cloudflare:
  email: 'keyvanfatehi@gmail.com'
  token: '7fea8149b27436d01540c7afe3dc14af7ef81'
redis: 
  host: '127.0.0.1'
  port: 6379
  options: # Options listed at https://github.com/mranney/node_redis
    auth_pass: null # Set it to the password or leave it as null which is default
mongodb: 'mongodb://localhost/saasbox-dev'
cookie_name: 'connect.sid'
cookie_secret: 'secrets'
email:
  service: Mailgun
  auth:
    user: postmaster@deadsimplecloud.com
    pass: db548f7ff45ad59c361b4898346d223e
mailhide:
  publicKey: 01zlt8r3De11zvokfkp1SA9A==
  privateKey: 9aa1f2990e57bfef18e90b90a064578c
cloud_providers: 
  DigitalOcean:
    token: 5bd56c18a91085b749eb711fe3e6673ffb3a836abeb2495bc959ee0c2bd491cb
ssh_public_key: ssh-rsa AFAAB3NzaC1yc2EAAAADAQABAAABAQDHW/TYp5/pSPoEzsStbdHjIbScQiNPvNFfJFrKa1nYtYQf97Fjn73qPR/XkgpVela3kkdbhxvKBFFRq3T0Gy/JuExueUk4toSwvpdn67VFd234UtXnweaFbzYeJXwZ7df1dpBnGMnbr38fdPgJl6mgVuQEKGLQH6VPtSpxalnExjHnTiZ5hEbObm54fPGf0k73VCEnc7PjSJL3V8/f0I0+xCZbL8eWP6FKDcGsR5LE3Okm58WOIqVd/RK5Pjaqm11xAXlpIIzSUQ4c7LaQaAUmDoZJhlnDhdVE4PDtjJp/t3l0ywmi07L8JNF4sbE/8nFrCDSnuFaSgGeRnSnwzyeN keyvan@keyvans-MacBook-Air.local
