---
app_name: 'Upstream'
web_title: 'Upstream -- simple as a service'
zone: upstreamapp.com
dns:
  host: box.upstreamapp.com
  email: dnsctl@upstreamapp.com 
  password: YpGymLupKBqV3bQR9bkdEqratC
redis: 
  host: '127.0.0.1'
  port: 6379
  options: # Options listed at https://github.com/mranney/node_redis
    auth_pass: null # Set it to the password or leave it as null which is default
mongodb: 'mongodb://localhost/saasbox-dev'
cookie_name: 'connect.sid'
cookie_secret: 'secrets'
email:
  port: 587
  host: box.upstreamapp.com
  auth:
    user: no-reply@upstreamapp.com
    pass: CuQ3zzybTHK6vrRqEMXy
cloud_providers: 
  DigitalOcean:
    token: 5bd56c18a91085b749eb711fe3e6673ffb3a836abeb2495bc959ee0c2bd491cb
ssh:
  publicKeyPath: etc/ssh/id_rsa.pub
  privateKeyPath: etc/ssh/id_rsa
# Uncomment in production
# ssl:
#   keyPath: playbook/roles/common/files/ssl/cert.key
#   certPath: playbook/roles/common/files/ssl/cert.pem
loggly:
  subdomain: keyvan
  token: dc3c6cef-d5b9-4061-bcc7-c64e8390cdde
