---
app_title: 'Pillbox.io'
zone: pillbox.io
cloudflare:
  email: 'keyvanfatehi@gmail.com'
  token: '7fea8149b27436d01540c7afe3dc14af7ef81'
redis: 
  host: '127.0.0.1'
  port: 6379
  options: # Options listed at https://github.com/mranney/node_redis
    auth_pass: null # Set it to the password or leave it as null which is default
mongodb: 'mongodb://localhost/saasbox-dev'
cookie_name: 'connect.sid'
cookie_secret: 'secrets'
email:
  port: 587
  host: box.pillbox.io
  auth:
    user: support@pillbox.io
    pass: butqfP6xuUAkWDU4
mailhide:
  publicKey: 01zlt8r3De11zvokfkp1SA9A==
  privateKey: 9aa1f2990e57bfef18e90b90a064578c
cloud_providers: 
  DigitalOcean:
    token: 5bd56c18a91085b749eb711fe3e6673ffb3a836abeb2495bc959ee0c2bd491cb
ssh:
  publicKeyPath: etc/ssh/id_rsa.pub
  privateKeyPath: etc/ssh/id_rsa
# Uncomment in production
# ssl:
#   keyPath: playbook/roles/common/files/ssl/pillbox_io.key
#   certPath: playbook/roles/common/files/ssl/star_pillbox_io.pem
