---
- name: Copy supervisor config file
  template: src=supervisor/app.conf
        dest=/etc/supervisor/conf.d/app.conf
        owner=root group=root mode=0644

- name: Copy haproxy custom config file
  copy: src=haproxy.cfg dest=/etc/saasbox/haproxy-custom.cfg
        owner=root group=root mode=0644

- name: Restart and verify reachable
  command: /usr/local/bin/restart_and_verify
  tags:
    - restart
