---
- name: Install apt packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - supervisor
    - build-essential
    - nodejs
    - npm

- name: Create node symlink
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
