---
- name: Copy github authorized private key
  copy: src=ssh/id_rsa
        dest=~/.ssh/id_rsa
        owner=root group=root mode=0400
  when: github_repo is defined
        
- name: Install git
  apt: name=git state=present update_cache=yes cache_valid_time=3600
  when: github_repo is defined

- name: Pull source from github
  git: repo=git@github.com:{{ item.repo }}
       accept_hostkey=True
       version=master
       dest={{ item.dest }}
  with_items:
    - repo: "{{ github_repo }}"
      dest: "{{ deploy_to }}"
    - repo: keyvanfatehi/.conf
      dest: /root/.conf
  when: github_repo is defined
  tags:
    - github
  notify:
    - Restart supervisor
#     - Rebuild (maybe need to do npm rebuild)
    - Pause
    - Verify reachable
