---
# We'll use supervisor to manage haproxy our way
- service: name=haproxy enabled=no state=stopped

- name: Copy supervisor config for haproxy
  copy: src=supervisor/haproxy.conf
        dest=/etc/supervisor/conf.d/haproxy.conf
        owner=root group=root mode=0644

- name: Copy haproxy common config file
  copy: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg
        owner=root group=root mode=0644
