---
copy_certs: True # XXX need to finish node-digicert and generate these proper
github_deploy_key: ../../agent/files/id_rsa
github_repo: keyvanfatehi/saasbox-agent.git
deploy_to: /opt/saasbox/agent
verifies:
  - url: "https://{{ name }}.{{fqdn}}/api/v1/version"
    status: 200
exposed_ports:
  - 22
  - 80
  - 443
